name: CI
on: 
  push:
    branches:
      - main
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run:  |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt install -y gcc-10
          sudo apt install -y g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
          sudo update-alternatives --config gcc
          sudo apt-get install -y libboost-all-dev cmake
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Test
        run: |
          cd build
          ctest --verbose


      